### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by ririko5834** [joshterrill/hushnote#14] opened 2020-12-16 09:27 UTC
Hi, can you please add these features?
- Remove  `Destroy message after being read` notes after 60 days from database when they are not read.
- Add option to setup custom password for notes. That if note is password protected user will need to enter the correct password to show the note.
- Make dark theme option
- Add option to setup expiration also on api

**Comment by ririko5834** [comment] 2020-12-16 09:58
Also i am getting this error:
```
the options [useUnifiedTopology] is not supported
```

**Comment by ririko5834** [comment] 2020-12-16 10:15
And also can you make that notes what have ttl will be checked every 30 mins for expiration. Now the mongo is spammed with notes that nobody didnt clicked on.

**Comment by joshterrill** [comment] 2021-01-07 23:34
I am not able to reproduce any error such as 

```
the options [useUnifiedTopology] is not supported
```

So you'll need to provide some more information as to what's going on. Using the latest version of the code, with the correct configuration in the env file, everything appears to be working fine.

As for the other asks in your first message, some of these are good ideas such as adding expiration functionality to the API, or adding custom passwords. If you wanted to submit a pull request for me to review with this functionality added, I will review it and possibly merge it if everything looks good. But I personally will not be able to code any of this for quite some time for at least a couple of months, if that.

**Comment by joshterrill** [comment] 2022-09-02 07:10
@ririko5834 Just wanted to let you know that the latest version of this app has a setting in it to automatically delete stale messages after some defined time. I think I'll also implement expiration on the API as you mentioned, and maybe a dark theme. Not sure if I'll end up implementing a password or not. There are just so many other apps that already work that way, but I'll think about it. If you wanted to submit a PR for it, I'd merge it! :D

**Comment by joshterrill** [comment] 2024-04-16 16:25
Closing this out as I've implemented the items listed above that I wanted to implement. Thanks for the suggestions, I hope you get to check it out again some time soon.

**Closed as completed by joshterrill** 2024-04-16 16:25 UTC
